apiVersion: v1
kind: Service
metadata:
  name: devops-frontend-svc
spec:
  selector:
    app: devops-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: devops-backend-svc
spec:
  selector:
    app: devops-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
