name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]
    paths: ["ant-design-vue-jeecg/**"]

jobs:
  nodejs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: 'yarn'
      - run: cd ant-design-vue-jeecg
      - run: yarn install
      - run: yarn run build